language: node_js
node_js:
- node
env:
  global:
    secure: czG6eZFH4G2GaBES+8s8feshydOXTH3+SfVwm9AYfUaUJljPlyNVmsy6xritf+njMqmWDsGg4cGc4ZqyYiZMeDUNYVzpFB7pTUDEOIe2ztP8QfucNnO6ThVVlAJYwpD+uv3E1ECfk3psS/nMzaXw/+OwUY5Qx8fPRfeaG2AOZRxG6h1mMYO+c7af9Lbrre1nNm4HhS4T0Qodl3/wPbzf7xn0+TdfGwypCDdppcA+kbzuCWK1nc3pKeg4ezA50y1MGupdWRh8r1lITv/ziytG54GeWFnjefyQ1gnBcr4NDRKuoBRreh6maDYKF0M7GbVGUQ1xHlacjl7QwqE6TyMdVxamP7fl/a+BqEFA7Kv4i+ZPYpcwlD/KYUZWLhLrKDhvNuIj89eZggbEjKiMaoBLO5fy41PaiPSGuBXqwwLAJI2XfUJirwM0Mmr4n/zzV2wffaTcDIw88WmzVt5fbLJcoe59xRVK0VZWTw6RmoRNLrSddcAEncXlp2/UKTIwk2VU4AxHwIVlf86hPnBJ3SISp6s0k+XO6jcm2jbYGCY+/2ogYzzL52clllV9J6gxX587s/1sgbDMHmgHHD+/0vRO3F7tH7+nXuIR+27b2RKVcH1jwGjtFFANw1V9CwNzoMKWictwZMB4Cpn9i6YfkOQtUNpoYtuxfNd1qMwgsIVwEws=
before_install: yarn global add greenkeeper-lockfile@1
before_script: greenkeeper-lockfile-update
after_script: greenkeeper-lockfile-upload
addons:
  sonarcloud:
    organization: "viewstools" # the key of the org you chose at step #3
    token:
      secure: wyKhWxaquaWgnHfi2WjHHtmVbRPPgE9dAYhiRi8j2HHZ16wium6xgSi1TiAyh3JgqIbI1siCDA+PcyHnc+Lf8n0HerU+HcE2ZPiy/zkdcwk4uwyLyKuFxp05znYCmXJ6wv7OLVYIjTWKOrC6qZaAn17LRtZCB2SD9VQ9jw+dzFbWKJ7SLecngcTS/DdSocXFiLUAkxLnmmy6gGCUatXgvSniyb5jdG3p0zQydjXqcOW6CPJcCdkGNPZf901Bpv2JerMLwjKUCfMIeYK/UpnJ9waNePRyOzXEzfjPcNuljyif+2xqNA5nPCTpOSaLK2bTW5/WT211ldAfxJV4aew/KuqEsef5jcuMgbsAcRDY4qk1HANKsxq2KJWzPqmJ0onDoJQzUFihVyf7/tq7d8tUttmf8LIV177qu0fe6ojWNmuGy7zAAiN83Oct45AfuaoxFSiAsxvr7ol7ynsouiZaZTkq19ewhsqDPrv8x8gJyq3Ymsfe6Auef0vMBVMDf8hWRWHnLZDQpSo3gSakXDa1TD7g+th7Cvlf6PcIrVDRQmVP1Hcjl/BhuRU9PqchNUBlowhTEFoliZd+Ofn2Vh6bZ6nlpBg1EbgkagVQ4VA39np5KJ1jSSbUtY6zBcNithHd63d6Vm4Lq6in01DmW2P5M2VZfIt5YDRNXYob9OT7lZk=
script:
  - sonar-scanner
